### ISSUE TITLE
사전 과제 피드백 리팩토링: TODO 앱 개선

### ISSUE THREAD

**Issue by ejaman** [ejaman/wanted-pre-onboarding-challenge-fe-1#1]
## 🔨 이슈 설명
최소한의 프로젝트인 todo 가볍지만은 않다!
<br />

## 📑 완료 조건
- [ ] UI 고려( loading, alert/dialog, snackbar: 실패시, 확인시 안내 필요)  
- [ ] redux toolkit 사용( 써봐야 안다!)
- [ ] 시멘틱 태그 적용
- [ ] 관심사 분리( 한 번에 한가지 일만, view- 화면 그려주기/logic - api 통신, 서비스 정책 등) 
- [ ] 의존성 역전(바꿔도 코드를 덜 바꾼다!)
- [ ] 변수명 수정( 변수명 (How vs What)을 선택하여 개발자의 의도를 드러내야한다, btn ➡️ button)

참조!
- 타입별 변수명
    - boolean : `is-`, `has-`, `can-`, ...
    - function : `get-`, `handle-`, `submit-`, …
    - array : `-s` (ex. `users.map(user ⇒ user.id)`), …
- 피해야 할 변수명
    - `data`, `info`, `foo`, `user1`, `mdhms`, …

<br />
리팩토링 전 노션 읽기!
<br />
<br />

## 💭 작업 기한
이번주 토요일까지(22.08.13)
<br />
